### ISSUE TITLE
[EXE] Implementing naive bayes algorithm from scratch

### ISSUE THREAD

**Issue by AayushK47** [gimseng/99-ML-Learning-Projects#100]
#### Learning Goals

Naive Bayes algorithm is one of the most simplest yet powerful ML algorithm out there, often used as a baseline for text based classification. Understanding the working of this algorithm will help in understanding:-

- Conditional probability
- Bayes theorem
- Laplace smoothing

### Exercise Statement
[Explain and describe what the exercise is]
The objective of this exercise is to implement the Naive Bayes algorithm along with using python 3 and numpy. The dataset to be used is [Haberman's Survival Dataset](https://www.kaggle.com/gilsousa/habermans-survival-data-set)

### Prerequisites 

You must have the basic understanding of what machine learning is, what is supervised and unsupervised learning, what is classification, etc. Knowledge of python 3 and numpy if also required.

### Data source/summary:
[Haberman's Survival Dataset](https://www.kaggle.com/gilsousa/habermans-survival-data-set) is a dataset containing cases from a study that was conducted between 1958 and 1970 at the University of Chicago's Billings Hospital on the survival of patients who had undergone surgery for breast cancer. Click [here](https://www.kaggle.com/gilsousa/habermans-survival-data-set) to learn more about this dataset.

### Further Links:

- To understand the Naive Bayes Algorithm, check out [this](http://shatterline.com/blog/2013/09/12/not-so-naive-classification-with-the-naive-bayes-classifier/) wonderful blog by [ShatterLine](http://shatterline.com/blog/)

- Check out this amazing [medium article](https://towardsdatascience.com/will-habermans-survival-data-set-make-you-diagnose-cancer-8f40b3449673) by[ Pratik Mirjapure](https://towardsdatascience.com/@mirjapurepratik) to understand the Haberman's Survival Dataset better.

**Comment by gimseng** [comment]
Great idea @AayushK47 ! If you already have some codes available to get started, feel free to check out our previous projects and contributing guidelines to see how we structure things here.

**Comment by glitch401** [comment]
Greetings, could i get started with this issue ?

**Comment by gimseng** [comment]
Hi @glitch401 it seems like PR #113 has been submitted to address this. Perhaps you could follow the PR thread there, and if @glitch401 needs some help, maybe you could assist on that.
