### ISSUE TITLE
[EXE] Health Insurance Cross Sell Production

### ISSUE THREAD

**Issue by tanviagwl98** [gimseng/99-ML-Learning-Projects#108]
#### Learning Goals
Learn the concept of KNN algorithm for classification.

### Exercise Statement
This exercise helps in classifying likelihood of a person to get insurance policy for his/her vehicle based on different factors including age, gender, having health insurance etc. 

### Prerequisites 
Must know the basic statistics and a programming language and concepts of scikit-learn.

### Data source/summary:
This data is available on Kaggle, a task open for anyone interested to take up.
 
### (Optional) Suggest/Propose Solutions
I have a solution notebook for this using KNN available on my Kaggle profile and would love to share my contribution by creating a  pull request.

### (Optional) Further Links/Credits to Relevant Resources:
This task is available [here](https://www.kaggle.com/anmolkumar/health-insurance-cross-sell-prediction)

**Comment by AjayKhalsa** [comment]
Looks good @tanviagwl98 Feel free to make a PR when you are ready

**Comment by gimseng** [comment]
@tanviagwl98 Thanks for contributing !
