### ISSUE TITLE
[DOC] Add hacktoberfest as a topic for this repo

### ISSUE THREAD

**Issue by AjayKhalsa** [gimseng/99-ML-Learning-Projects#114]
Hacktoberfest has made participation for maintainers to the event as opt-in
https://hacktoberfest.digitalocean.com/hacktoberfest-update
@gimseng To get contributions for hacktoberfest you would need to add a 'hacktoberfest' topic in the about section.
Refer to the above guide for more info.

**Comment by gimseng** [comment]
Hi @AjayKhalsa thanks ! I just did that. I see that you/someone else added the appropriate label for PR. Thanks ! Feel free to close this when you are satisfied.
