### ISSUE TITLE
Idea for exercise (CNN on MNIST data: handwriting digit classification)

### ISSUE THREAD

**Issue by gimseng** [gimseng/99-ML-Learning-Projects#16]

**Comment by aarpit1010** [comment]
I can give this one a try, as I had done this as a practice before. But, if you could give me some time then I can do this by the end of this week.

**Comment by gimseng** [comment]
@aarpit1010 Excellent ! Thanks for volunteering. Of course, take your time. The whole point of open source contribution is to do so when you have time and enjoy doing so. Be sure to check out the updated contributing guidelines. I wrote down more details on the format which should be helpful.
