### ISSUE TITLE
Titanic exercise with PyTorch

### ISSUE THREAD

**Issue by gimseng** [gimseng/99-ML-Learning-Projects#26]
Seems like we have a Tensorflow solution, it will be nice to have a PyTorch implementation of a simple neural network for survival classification.

**Comment by pragyakapoor** [comment]
Hey, can I work on this?

**Comment by gimseng** [comment]
Hi @pragyakapoor, thanks for the interest. This issue has been closed and fixed by PR #73 .
If you'd like to contribute PyTorch solutions for other projects, feel free to start a new issue ticket and later create a PR. Thanks !
