### ISSUE TITLE
Create category for different levels and topics?

### ISSUE THREAD

**Issue by gimseng** [gimseng/99-ML-Learning-Projects#5]
As number of exercises grow, we might want to restructure things a little to properly categorize them. For e.g., maybe intermediate should take 300 above and advanced/state-of-the-arts will take 900 above or something. Then within each range of numbers, we could have different topics taking different numberings.

**Comment by gimseng** [comment]
Create table of contents to organize the projects into chapters/topics/etc.

**Comment by gimseng** [comment]
@cundo92 Will you be interested in getting started on this?

**Comment by cundo92** [comment]
Yea I can take this one.

**Comment by gimseng** [comment]
@cundo92  go ahead ! Thanks for that !
