### ISSUE TITLE
[EXE] Ensemble and stacking methods

### ISSUE THREAD

**Issue by gimseng** [gimseng/99-ML-Learning-Projects#52]
#### Learning Goals
[Learning goals, bulleted/numbered list is preferred]
Starting with randomforest, adaboost, etc up to popular LightGBM, XGBoost, expose learners to a variety of bagging/boosting/ensemble/stacking techniques.

This could be a series of 4-5 exercises.

**Comment by anandravishankar12** [comment]
Hey,
I was wondering if I could contribute to this issue. This would be my first OSS contribution. I have previously worked in algorithm development area. and presented a paper on a novel pipeline in IEEE CONECCT 2020. Kindly find attached a python file for the first exercise along with file structure (commented out) and sample code implementation. Let me know if I can contribute in any manner.
[https://github.com/anandravishankar12/OSS_1](url)

**Comment by gimseng** [comment]
Hi @anandravishankar12 thanks for the interest and the help ! And yes, please contribute ! Please check out the contributing guide as well as a few of the projects to see what are the structures and format/convention. Otherwise, its all very informal and flexible. Feel free to create a PR once you created the codes and figured out how to do all the git stuff. Its ok to fumble and make mistakes as first contribution, we will help each other during the PR discussion.

Again, thanks !

**Comment by anandravishankar12** [comment]
Have submitted my first PR. Kindly review it and get back to me with the required changes. Thanks you.
