### ISSUE TITLE
Recruiting for core

### ISSUE THREAD

**Issue by gimseng** [gimseng/99-ML-Learning-Projects#6]
Anyone interested in maintaining and developing this repo as core team? Please comment below

**Comment by Ar-Kareem** [comment]
I'm interested and can definitely contribute on maintaining and developing during my free time.

**Comment by firebolt7** [comment]
I'm interested

**Comment by dbbvitor** [comment]
I'm interested!

**Comment by cundo92** [comment]
I’m interested. I can’t offer any ML experience but would be interested with documentation. I have plenty of experience with creating and maintaining GitHub wikis.

**Comment by malwaredllc** [comment]
I'm interested. I have experience creating and maintaining large open source projects, as well as some ML experience (still learning though). By the way, I tried to join the discord channel but it didn't work for me? Anyone else had an issue with this?

**Comment by elkhader** [comment]
I'm interested

**Comment by gimseng** [comment]
Thanks everyone for the replies ! Please see if you create some exercises. If the current readme and other docs are not clear, please create an issue and suggest how to fix it.

@malwaredllc the discord link is https://discord.gg/GRQXuq , and I (and a few others) seem to be able to join. Try again and let me know if you still can't join.

**Comment by rexdivakar** [comment]
Interested !!

**Comment by gimseng** [comment]
Great, thanks everyone for the interest. I will add you all as collaborator on GitHub. If you are not too experienced using GitHub (fork,clone, push, pull and etc), maybe try to submit issues and create pull request.

For those who are experienced in GitHub already, please let me know. Maybe send me a direct message on the discord channel. It will be a great help for you to start reviewing the pull request.

**Comment by gimseng** [comment]
So I just added everyone above to contributor access. Please join discord. We have also set up a core team chat room. Please send me (JimNg) or DBlackBird a direct message on discord to get access to the chat room. We will then take the more informal discussions there. Looking forward to getting know you all and thanks for the interest !

**Comment by gimseng** [comment]
Hey all, I will probably   close this issue within a week. 

Hopefully I will get a semi structured project up within a week-ish. After which, probably if there is at least 2-3 active maintainers, I could implement a requirement for pull request to be approved by 2-reviewers. Currently, I do a lot of minor changes so its sort of hard to wait, plus I am not sure how frequently other core people check and review pull request.

Finally, please show some involvement, either through discord, create issues or pull request, or do something so that I know that you are active and still be interested. It doesn't have to be a big thing, suggestions or questions on issue ticket are good enough. 

When I close this issue, I will phase out inactive core team members as well.

**Comment by gimseng** [comment]
@aarpit1010 @Ar-Kareem @elkhader @firebolt7 @malwaredllc @rexdivakar Just to check that you got the collaborator invite for the project. As I mentioned above, I'll start organizing the team a little, so if you are not active, please let me know. If you are still interested, do accept the access invitation. Perhaps in the next days or two, create an issue or comment on an issue/pull request, so that I know that you are still active.
