### ISSUE TITLE
[IMP] Data source description for the data in exercise 002

### ISSUE THREAD

**Issue by gimseng** [gimseng/99-ML-Learning-Projects#65]
More detailed descriptions and provide credit to the source of the housing dataset in exercise 002. Please do so in `/exercise/readme.md` and/or in the exercise notebook.

**Comment by vardhanaleti** [comment]
Hey, is anyone adding the link to the source? 
I'd found the link and made a PR.

**Comment by gimseng** [comment]
Hi @vardhanaleti, thanks for the comment/issue. I'll comment/make suggestions on the PR. Thanks !
