### ISSUE TITLE
[IMP] Provide description and credit/source for data used in exercise 004

### ISSUE THREAD

**Issue by gimseng** [gimseng/99-ML-Learning-Projects#66]
As stated in the title. If this is copied/scraped somewhere, provide a source of that. At least provide description.

@Rajwrita Maybe you would be able to help. Thanks !

**Comment by Rajwrita** [comment]
Hi gimseng, I have made the dataset by combining several songs from the [Arctic Monkeys](https://www.arcticmonkeys.com/). I have not taken the data set from anywhere.

**Comment by gimseng** [comment]
@Rajwrita Thanks ! If you wrote up the lyrics by memory, then I guess its fine. Maybe just provide the titles of the songs. Otherwise, if its from Arctic Monkey's or wiki's websites on the lyrics, maybe its useful to provide links to those webpages.

**Comment by Rajwrita** [comment]
Sure! I'll add the links :)

**Comment by gimseng** [comment]
@Rajwrita  Thanks !

**Comment by gimseng** [comment]
@Rajwrita While you are at it, could you provide a concise description of the models/techniques you used in your solution in the `solution/readme.md`? Something along the line of (001)[https://github.com/gimseng/99-ML-Learning-Projects/tree/master/003/solution] or (003)(https://github.com/gimseng/99-ML-Learning-Projects/tree/master/003/solution)

**Comment by Rajwrita** [comment]
Sure, I'll add it in a day.
