### ISSUE TITLE
Beginner's ML coding exercises

### ISSUE THREAD

**Issue by aarpit1010** [gimseng/99-ML-Learning-Projects#7]
Goal: To learn one of the most important part of doing a ML project/question, Data Wrangling and then perform basic Classification based Supervised Learning Algorithms.

What and Why : To predict the survival of the passengers of The Titanic. We will be doing this to be able to have a hands-on learning experience for classification problems and an introduction to solve various ML problems. It might even give you a head start on Kaggle. 

Apply Logistic Regression, Decision Tree, Random Forest, Gaussian Naive Bayes and much more

Bonus and extra credits : Understanding regularization,  model selection, confusion matrix and cross validation.

**Comment by gimseng** [comment]
@aarpit1010 Great starter project ! Do you want to create this exercise and/or the solution? We are still building contributing guidelines, but if you are used to git and GitHub, feel free to jump right in. If you have questions or need help, please feel free to ask. Things are a bit loose at the moment, so any format or style is fine.
