### ISSUE TITLE
[IMP] 005 sentiment analysis missing codes

### ISSUE THREAD

**Issue by gimseng** [gimseng/99-ML-Learning-Projects#76]
The notebook seems to have some missing codes at the end regarding distributing positive and negative reviews.

@tejasvi541 Could you take a look since you last worked on it? Please fork the current/updated master file and add your codes to the end, if you have them. Thanks !

**Comment by tejasvi541** [comment]
Hey @gimseng ,
The notebooks is complete from my side, the mentioning the distribution of positive and negative reviews i have written at the end is actually completed by me in the above cells where i defined the Review Container class in cell number 8.
As it was added by me in last steps so i wrote the description about it in the end.
Thank you.

**Comment by gimseng** [comment]
@tejasvi541 Thanks for the reply. From my side (and checking out the original version in your PR), the nb ends with `We will add one more container class above which will evenly distribute the positives and negatives in cell 8.` 

From your side, are there more codes after that? If yes, could you add to the current version on the repo? If no, then I don't quite understand the last sentence of the nb. I saw `train_container` and `test_container` being defined, but weren't used at all. I assume that after the last sentence, you might want to do train and evaluation using these two evenly-distributed data. Or do you want to leave as an exercise for the reader?

**Comment by tejasvi541** [comment]
Hi @gimseng ,
I will have a look to the notebook again thoroughly and will make the desired changes which you have mentioned, incase I would not make that issue resolve , I will let you know about that.
Thanks..
