### ISSUE TITLE
[DOC] Number pages on the basis of difficulty or how are they related to other projects

### ISSUE THREAD

**Issue by AjayKhalsa** [gimseng/99-ML-Learning-Projects#93]
For now, the projects are assigned the number on a first come first serve basis. So if we could categorize it now, it would be way easier when we have a lot of projects. For example, Linear Regression should come before Titanic. The least we could do is classify projects as Machine Learning, Deep Learning, NLP etc

**Comment by gimseng** [comment]
@AjayKhalsa Great idea ! Feel free to use your judgements in creating categories and links. We probably need to go through a few iterations once the number of project gets bigger. Many thanks !

**Comment by gimseng** [comment]
I think this is related to #5 too.

**Comment by AjayKhalsa** [comment]
Oh I didn't see that, check out the structure I made and see if it works

**Comment by gimseng** [comment]
Cool thanks @AjayKhalsa. I already merge your PR.
